
# DataSource Config

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:postgresql://47.113.102.153:5432/project2
#    url: jdbc:mysql://10.28.141.164:3306/e-commercial
#    url: jdbc:mysql://localhost:3306/ASE # local
#    url: jdbc:mysql://aseDB:3306/ASE # docker
#    url: jdbc:mysql://47.250.53.77:3306/ASE
    url: jdbc:mysql://localhost:3307/ASE # port to remote server
    username: root
    password: alibabaRoot

logging:
  level:
    root: warn
    com.example.springboot: trace
  pattern:
    console: '%p%m%n'

server:
  port: 8080

