
# DataSource Config

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:postgresql://47.113.102.153:5432/project2
#    url: jdbc:mysql://10.28.141.164:3306/e-commercial
    url: jdbc:mysql://localhost:3306/e-commercial
    username: root
    password: '1998610ajjqZH&'
#    url: jdbc:mysql://47.250.53.77/e-commercial
#    username: root
#    password: 'alibabaRoot'



logging:
  level:
    root: warn
    com.example.springboot: trace
  pattern:
    console: '%p%m%n'

server:
  port: 8080

